---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-all
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-all
  template:
    metadata:
      labels:
        app: health-all
    spec:
      containers:
        - name: health
          image: deepakvarshney5576/health-project:1.0
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: health-all
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: health-all
